# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd6bdd5b2202cc9c03a74d25a243e78ed1cb448aa294fc513395511f77a7fcfdc7304aeeca2c459c4b0e43dab1e15da8abd353ee6433e9c9c6733fb564dcfc4c

test:
  secret_key_base: 43a4417e654c26f49dfa042e6c95f6814dc4abc263d7631a3d839f21ac2bf6026a219be83d00b1b67145a3a88432b0fb34d93e926ea22716bde304f1eaad292b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
